FROM node:22-slim AS base

ENV PNPM_HOME="/usr/local/bin"
RUN corepack enable pnpm \
  # Force Corepack to download PNPM before proceeding.
  && pnpm -v


FROM base AS server

WORKDIR /app

CMD [ "pnpm", "--filter=server", "dev:start" ]


FROM base AS client

WORKDIR /app

CMD [ "pnpm", "--filter=client", "dev" ]