# Build package first with dev dependencies included.
FROM node:lts-alpine3.23 AS builder

WORKDIR /app

COPY package*.json .
RUN npm ci

COPY . .
RUN npm run -w @blog/client build

# Serve from Nginx image keeping only build files.
FROM nginx:stable-alpine3.23-perl

COPY --from=builder /app/client/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]