# Build using Node image.
FROM node:lts-alpine3.23 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . .

RUN npm run build

# Serve from Nginx image keeping only build files.
FROM nginx:stable-alpine3.23-perl

COPY --from=builder /app/dist /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]